from django.urls import path
from . import views

urlpatterns = [
    path('home/', views.home, name = 'blog_home'),
    path('post_list/', views.post_list, name ='post_list'),
    path('e_news/e_news01/', views.eachNews, name='e_news'),
    path('e_news/e_news02/', views.eachNews02, name='e_news'),
    path('e_news/e_news03/', views.eachNews03, name='e_news03'),
    path('e_news/e_news04/', views.eachNews04, name='e_news04'),
    path('e_news_today/', views.eNews, name='eNewsToday'),
    path('e_news_today/?date=30November18&p=page1/', views.eNews, name='querryENewsToday'),
    path ('create/', views.product_create_view, name='product_create_view'),
    path ('new_user/', views.userRegistration, name='userRegistration'),
    path ('reg/', views.userReg, name='userRegistration'),
    path('single_post/<post_id>/', views.single_post, name='single_post'),
    path('register/', views.RegisterUserView, name='authenticRegister'),
    path('registration/', views.Registration, name='Reg'),
    path('login/', views.login_view, name='Login'),
    path('save/', views.home, name='homesave'),
    path('developer/', views.developerView, name='dev'),
    path('about/', views.aboutView, name='about'),
    path('profile/', views.django_image_and_file_upload_ajax, name='profileImage'),
    path('contact/', views.contactView, name='about'),
    path('e_news_today/gg/', views.specific, name='specificNews'),
    path('e_news_today/?cat=business/', views.specific, name='dfdf'),
    path('e_news_today/?cat=sports/', views.specific, name='dfd'),
    path('e_news_today/?cat=entertainment/', views.specific, name='dfd'),
    path('e_news_today/?cat=science_technology/', views.specific),
    path('e_news_today/?cat=lifestyle/', views.specific),
    path('e_news_today/?cat=comics/', views.specific),
    path('e_news_today/?cat=cartoons/', views.specific),
    path('e_news_today/?cat=jobs/', views.specific),
    path('e_news_today/?cat=opinions/', views.specific),
    path('e_news_today/?cat=international/', views.specific),
    path('e_news_today/?cat=circulations/', views.specific),
    path('e_news_today/?cat=advertisement/', views.specific),
    path('e_news/education/', views.educationView),
    path('e_news/business/', views.businessView),
    path('e_news/sports/', views.sportsView),
    path('e_news/entertainment/', views.entertainmentView),
    path('e_news/science/', views.scienceView),
    path('e_news/lifestyle/', views.lifestyleView),
    path('e_news/comics/', views.comicsView),
    path('e_news/cartoons/', views.cartoonView),
    path('e_news/jobs/', views.jobsView),
    path('e_news/opinion/', views.opinionView),
    path('e_news/international/', views.internationalView),
    path('e_news/circulation/', views.circulationView),
    path('e_news/advertisements/', views.advertisementView),

]
