# Generated by Django 2.1.2 on 2018-11-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_auto_20181123_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=30)),
                ('email', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
