# Generated by Django 2.1.2 on 2018-11-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Newusers',
        ),
    ]
