# Generated by Django 2.1.2 on 2018-11-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_auto_20181124_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='occupation',
        ),
    ]
