# Generated by Django 2.1.2 on 2018-11-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0011_auto_20181124_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
