# Generated by Django 2.1.2 on 2018-11-25 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0014_auto_20181125_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
