# Generated by Django 2.1.2 on 2018-11-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0016_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('pageNumber', models.IntegerField(max_length=16)),
                ('position1', models.ImageField(blank=True, upload_to='row1column1')),
                ('position2', models.ImageField(blank=True, upload_to='row1column2')),
                ('position3', models.ImageField(blank=True, upload_to='row1column3')),
                ('position4', models.ImageField(blank=True, upload_to='row2column1')),
                ('position5', models.ImageField(blank=True, upload_to='row2column2')),
                ('position6', models.ImageField(blank=True, upload_to='row2column3')),
                ('position7', models.ImageField(blank=True, upload_to='row3column1')),
                ('position8', models.ImageField(blank=True, upload_to='row3column2')),
                ('position9', models.ImageField(blank=True, upload_to='row3column3')),
            ],
        ),
    ]
