# Generated by Django 2.1.2 on 2018-11-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0017_enewspaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ENewsUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('pageNumber', models.CharField(choices=[('page1', 'Page1'), ('page2', 'Page2'), ('page3', 'Page3'), ('page4', 'Page4'), ('page5', 'Page5'), ('page6', 'Page6'), ('page7', 'Page7'), ('page8', 'Page8')], max_length=100)),
                ('position', models.CharField(choices=[('r0c0', 'Page Topper'), ('r1c1', 'Row 1 Column 1'), ('r1c2', 'Row 1 Column 2'), ('r1c3', 'Row 1 Column 3'), ('r2c1', 'Row 2 Column 1'), ('r2c2', 'Row 2 Column 2'), ('r2c3', 'Row 2 Column 3'), ('r3c1', 'Row 3 Column 1'), ('r3c2', 'Row 3 Column 2'), ('r3c3', 'Row 3 Column 3')], max_length=100)),
                ('category', models.CharField(choices=[('education', 'Education'), ('business', 'Business'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('science_technology', 'Science & Technology'), ('lifestyle', 'Lifestyle'), ('comics', 'Comics'), ('cartoons', 'Cartoons'), ('jobs', 'Jobs'), ('opinions', 'Opinions'), ('international', 'International'), ('circulations', 'Circulations'), ('advertisement', 'Advertisement')], max_length=100)),
                ('news', models.ImageField(blank=True, upload_to='news')),
            ],
        ),
        migrations.AlterField(
            model_name='enewspaper',
            name='pageNumber',
            field=models.IntegerField(blank=True),
        ),
    ]
