# Generated by Django 2.1.2 on 2018-11-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0018_auto_20181130_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enewsupload',
            name='category',
            field=models.CharField(choices=[('topper', 'Topper Page'), ('education', 'Education'), ('business', 'Business'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('science_technology', 'Science & Technology'), ('lifestyle', 'Lifestyle'), ('comics', 'Comics'), ('cartoons', 'Cartoons'), ('jobs', 'Jobs'), ('opinions', 'Opinions'), ('international', 'International'), ('circulations', 'Circulations'), ('advertisement', 'Advertisement')], max_length=100),
        ),
    ]
