# Generated by Django 2.1.2 on 2018-12-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0019_auto_20181130_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='tinytest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
