# Generated by Django 2.1.2 on 2018-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0023_advertisement_business_cartoons_circulation_comics_entertainment_international_jobs_lifestyle_opinio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, upload_to='profile_image')),
            ],
        ),
    ]
