# Generated by Django 2.1.2 on 2018-12-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0024_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='enewspaper',
            name='position0',
            field=models.ImageField(blank=True, upload_to='row0column0'),
        ),
    ]
